--colocando check
ALTER TABLE UNIDADE_EMPRESARIAL ADD CONSTRAINT CK_TP_PESSOA_UE CHECK ((TP_PESSOA = 'PJ' AND LENGTH(NU_RAIZ_CNPJ) = 8 AND NU_CPF IS NULL) OR (TP_PESSOA = 'PF' AND LENGTH(NU_CPF) = 11 AND NU_RAIZ_CNPJ IS NULL));

--colocando index 
CREATE INDEX IX_NO_RAZAO_SOCIAL_UNIDADE_EMP ON UNIDADE_EMPRESARIAL (NO_RAZAO_SOCIAL);-- TABLESPACE SCAD_TS; SOMENTE SE O DATABASE DEFAULT N\u00C3O ESTIVER DEFINIDO PARA O SCAD

--colocando unique indexado
ALTER TABLE UNIDADE_EMPRESARIAL ADD CONSTRAINT UN_TP_PESSOA_RAIZ_CNPJ_CPF_UE UNIQUE (TP_PESSOA, NU_RAIZ_CNPJ, NU_CPF);

--colocando check
ALTER TABLE ESTABELECIMENTO ADD CONSTRAINT CK_NU_CNPJ_ESTABELECIMENTO CHECK (NU_CNPJ IS NULL OR LENGTH(NU_CNPJ) = 14);

--colocando index  nas FKs
CREATE INDEX IX_SQ_UE_ESTABELECIMENTO ON ESTABELECIMENTO (SQ_UNIDADE_EMPRESARIAL);-- TABLESPACE SCAD_TS; SOMENTE SE O DATABASE DEFAULT N\u00C3O ESTIVER DEFINIDO PARA O SCAD

--colocando unique indexado
ALTER TABLE ESTABELECIMENTO ADD CONSTRAINT UN_NU_CNPJ_ESTABELECIMENTO UNIQUE (NU_CNPJ);

--colocando unique indexado
ALTER TABLE INSCRICAO_ESTABELECIMENTO ADD CONSTRAINT UN_NU_INSCRICAO_ESTADUAL_IE UNIQUE (NU_INSCRICAO_ESTADUAL);